spring.application.name=showtime-service
server.port=8083

spring.datasource.url=jdbc:sqlserver://cinema-db.cqv8o0gkkhu0.us-east-1.rds.amazonaws.com:1433;databaseName=EgyCinema;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=ahmed01093908250
Port: 1433


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.enabled=false

